name: flutter_etu_remake
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  fluttertoast: ^7.1.4
  json_annotation: ^3.1.1
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  provider: ^4.3.2+3
  #显示html文本
  flutter_html: ^1.1.0

  #百度地图依赖包（工具包 定位包，地图包）
  flutter_bmfmap:  ^1.0.2 
  flutter_bmfutils: ^1.0.2  
  flutter_bmflocation: ^1.0.3

  #轮播图插件
  flutter_swiper: ^1.1.6
  #http库
  dio: ^3.0.10

  azlistview: ^1.1.0
  lpinyin: ^1.0.7

  address_picker: ^0.0.1

  fluwx: ^2.5.0+1

  table_calendar: ^2.3.2
  image_picker: ^0.6.7+17

  flutter_sound: ^4.0.0

  #环信im sdk
  im_flutter_sdk:  
    path: D:\Download\im_flutter_sdk-alpha\im_flutter_sdk-alpha/
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.5.1
  build_runner: ^1.6.1
  intl_translation: ^0.17.10+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # datas
    - assets/data/profile.json
    - assets/data/china.json  

    # images
    - assets/images/btn.png
    - assets/images/hoverBar.png
    - assets/images/icon_dlmm_nor.png
    - assets/images/icon_fh_nor.png
    - assets/images/icon_phone.png
    - assets/images/icon_sjh_nor.png
    - assets/images/login_bg.png
    - assets/images/icon_yzm_nor.png

    - assets/images/icon_wx_nor.png 
    - assets/images/icon_zfb_nor.png 
    
    - assets/images/icon_gd_nor.png

    - assets/images/icon_gwc_nor.png 
    - assets/images/icon_gwc_hover.png   
    
    - assets/images/icon_home_nor.png 
    - assets/images/icon_home_hover.png 

    - assets/images/icon_my_nor.png 
    - assets/images/icon_my_hover.png

    - assets/images/icon_sp_nor.png
    - assets/images/icon_sp_nor_hover.png

    - assets/images/icon_ss_nor_nav.png
    - assets/images/icon_ss_nor_nor_nav.png
    - assets/images/bg.png
    - assets/images/mine_bg.png

    - assets/images/man.png
    - assets/images/woman.png

    - assets/images/icon_dfk_nor.png
    - assets/images/icon_dfh_nor.png
    - assets/images/icon_dsh_nor.png
    - assets/images/icon_dpj_nor.png
    - assets/images/icon_sh_nor.png

    - assets/images/icon_shdz_nor.png
    - assets/images/icon_kf_nor.png
    - assets/images/icon_yqhy_nor.png
    - assets/images/icon_yjfk_nor.png
    - assets/images/pic_qsy_nor.png
    - assets/images/pay_bg.png

    - assets/images/icon_fzlj_nor.png
    - assets/images/icon_qqhy_nor.png
    - assets/images/icon_pyq_nor.png
    - assets/images/icon_sctp_nor.png
    - assets/images/icon_wxhy_nor.png

    - assets/images/bg_01.png
    - assets/images/balance_bg.png
    - assets/images/k_hover.png

    
    
    - assets/images/loading.gif
    
    


  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
